site_name: Strawberry GraphQL بالعربي
site_url: https://tareksamerr-cmd.github.io/strawberry-ar/
theme:
  name: material
  language: ar  # لتفعيل اتجاه النص من اليمين لليسار RTL
  palette:
    primary: red # لون الفراولة المميز

docs_dir: docs/ # المسار الذي يحتوي على ملفات الـ Markdown (.md)
