name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main # تأكد أن هذا هو اسم فرعك الرئيسي (Main أو Master)

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install poetry
          # تثبيت الاعتمادات الأساسية
          poetry install
          # تثبيت أدوات التوثيق يدوياً لتجنب خطأ Group not found
          pip install mkdocs-material mkdocs-static-i18n

      - name: Build and Deploy
        run: |
          # بناء التوثيق ورفعه لفرع gh-pages
          poetry run mkdocs gh-deploy --force
